### ISSUE TITLE
Final Project Feedback

### ISSUE THREAD

**Issue by philsinatra** [molynatep/idm221-mpt54#1]
## Code Quality

- Repetition in CSS file could be refactored. For example:

```css
nav {
    font-family: 'bebas', 'montserrat', sans-serif;
    color: #3D405B;
}

h1, h2{
    font-family: 'bebas','montserrat',sans-serif;
    color: #3D405B;
}
```

Why not group all three together?

```css
nav, h1, h2{
    font-family: 'bebas','montserrat',sans-serif;
    color: #3D405B;
}
```

## Functionality

- No major issues

## Design

- Some of your images are not designed for small screens. They are larger images that have been scaled to fit on small screens. Take Mei Tea as an example - the image is a tiny version of the entire menu. Is there a way you could design an image ideal for smaller screens that really shows off the work, instead of taking the full size image and simply scaling it down (art direction)? You did this on some of your Work specific pages, e.g. Giftster, going as far to not only build media that is optimized for small screens, but also animating the content in GIF format. 
- Art pieces look great. The page would be more interesting if you included captions with titles, or even better, included links so that each piece had its own page with details. As it is now, it's a dump of files without any form of organization or details (feels lazy compared to Work pages).

---

Overall a great start. I look forward to what you build next term.
